In [1]:
#libraries
import pandas as pd 
import numpy as np 
import json

In [2]:
#reading the csv file
df_1 = pd.read_csv(r"C:\Users\kumar\Documents\Bennett\Devops 5th Sem\Project\faculty_subject-wise-load_for-Odd_Sem_2022_1.csv")
df_1.head()

,AcademicYear,Semester,Faculty_Email,S.No.,First_Name,Last_Name,1_Core_Code,1_Core_Name,2_Core_Code,2_Core_Name,3_Core_Code,3_Core_Name,1_Elective_Code,1_Elective_Name,2_Elective_Code,2_Elective_Name,3_Elective_Code,3_Elective_Name,Remarks
0,JUL 2021-JUN 2022,ODD,aditya.bhardwaj@bennett.edu.in,1,Aditya,Bhardwaj,CBCA203,Operating System Concepts,CSET291,Data Structure Fundamentals,CSET501,Advanced Data Structures using Python,CSET334,Programming using C++,CSET452,Software Containerization in DevOps,CSET371,Big Data Analytics and Business Intelligence,NaN
1,JUL 2021-JUN 2022,ODD,akansha1.singh@bennett.edu.in,2,Akansha,Singh,CSET214,Data Analysis using Python,CSET225,Intelligent Model Design using AI,CSET301,Artificial Intelligence and Machine Learning,CSET344,Image and Video Processing,CSET381,Applications of AI,CSET334,Programming using C++,NaN
2,JUL 2021-JUN 2022,ODD,amit.biswas@bennett.edu.in,3,Amit,Biswas,CSET291,Data Structure Fundamentals,CSET212,Blockchain Foundations,CBCA204,Algorithm Design Strategies,CSET334,Programming using C++,CSET354,Cyber Security with Blockchain,CSET461,Cloud System Administration and Operations,NaN
3,JUL 2021-JUN 2022,ODD,anika.gupta@bennett.edu.in,4,Anika,.,CSET501,Advanced Data Structures using Python,CBCA204,Algorithm Design Strategies,CSET304,Competitive Programming,CSET459,Front-End UI Frameworks and Tools: Flutter and...,CSET334,Programming using C++,CSET370,Data Visualization and Dashboards,NaN
4,JUL 2021-JUN 2022,ODD,ankur.gupta@bennett.edu.in,5,Ankur,Gupta,CSET223,Augmented Reality Foundations,CBCA204,Algorithm Design Strategies,CSET291,Data Structure Fundamentals,CSET334,Programming using C++,CBCA252,Virtual Reality: Interface Application and Design,ECSE353L,Information Security,NaN

For Teachers preferences

In [3]:
#defining variables
name_1 = df_1["First_Name"] + " " + df_1["Last_Name"] 
id_11, id_2 = df_1.shape
elective_1 = df_1["1_Elective_Code"]
elective_2 = df_1["2_Elective_Code"]
elective_3 = df_1["3_Elective_Code"]

In [4]:
# instantiate an empty dict and array
field_obj_1 = {}
arr_1 = []
# convert teachers preferences to json file
for x in range(id_11):
    field_obj_1[x] = {'id' : x + 1 , 'name' : name_1[x], 'subjects': [{'subjectId': elective_1[x], 'L' : 0, 'T' : 0, 'P' : 0, 'prefOrder' : 1},{'subjectId': elective_2[x], 'L' : 0, 'T' : 0, 'P' : 0, 'prefOrder' : 2}, {'subjectId' : elective_3[x], 'L' : 0, 'T' : 0, 'P' : 0, 'prefOrder' : 3}]}
    arr_1.append(field_obj_1[x])
    with open('teacher_model_data.json', 'w') as f:
        json.dump(arr_1, f)

For Subject details

In [5]:
#reading second csv file
df_2 = pd.read_csv(r"C:\Users\kumar\Documents\Bennett\Devops 5th Sem\Project\faculty_subject-wise-load_for-Odd_Sem_2022_2.csv", skiprows = 2, dtype = object)
df_2.head()

,Cohort,Semester,Programme,Course Code,Course Title,Course Type,L,T,P,Credits,No. of lect batches,No. of Lab/Tut batches,Total Lect Load (Hrs),Total Tut Load (Hrs),Total Prac Load (Hrs),Total Load (Hrs)
0,2022-2026,I,BTECH,CSET101,Computational Thinking and Programming,Core Course,2,1,4,5,8,30,16,30,120,166
1,2022-2026,I,BCA,CBCA101,Digital Design and Computer Organization,Core Course,2,0,2,3,1,3,2,0,6,8
2,2022-2026,I,BCA,CBCA102,Computational Thinking with Python,Core Course,2,1,4,5,1,3,2,3,12,17
3,2022-2026,I,BCA,CBCA103,Web Technologies,Core Course,2,0,4,4,1,3,2,0,12,14
4,2022-2026,I,BCA,CBCA104,Mathematics Foundations,Core Course,3,1,0,4,1,3,3,3,0,6

In [6]:
id_2, id22 = df_2.shape
id = df_2[" Course Code"]
name = df_2["Course Title"]
programme = df_2["Programme"]
lectureBatches = df_2["No. of lect batches"]
tutLabBatches = df_2["No. of Lab/Tut batches"]
totalLecture = df_2["Total Lect Load (Hrs)"]
totalTutorial = df_2["Total Tut Load (Hrs)"]
totalPractical = df_2["Total Prac Load (Hrs)"]
L = df_2["L"]
T = df_2["T"]
P = df_2["P"]

In [7]:
# instantiate an empty dict and array
field_obj = {}
arr = []
# convert teachers preferences to json file
for x in range(id_2):
    
    field_obj[x] = {'id' : id[x] , 'name' : name[x], 'programme' : programme[x],'originalStructure': {'L' : L[x], 'T' : T[x], 'P' : P[x]}, 'lectureBatches' : lectureBatches[x], 'tutLabBatches' : tutLabBatches[x], 'totalLecture' : totalLecture[x], 'totalTutorial' : totalTutorial[x], 'totalPractical' : totalPractical[x], 'totalPractical' : totalPractical[x]} #,{'subjectId': elective_2[x], 'L' : 0, 'T' : 0, 'P' : 0, 'prefOrder' : 2}, {'subjectId' : elective_3[x], 'L' : 0, 'T' : 0, 'P' : 0, 'prefOrder' : 3}]}
    
    arr.append(field_obj[x])
    with open('subject_model_data.json', 'w') as f:
        json.dump(arr, f)